# Generated by Django 3.2.5 on 2021-08-10 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
