# Generated by Django 3.2.5 on 2021-07-20 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='search',
        ),
    ]
